name: tb-calitas
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9.18
  - calitas
  - pandas=2.2.1
  - nextflow=23.10.1
  - psycopg2=2.9.9
  - python-dotenv=1.0.1
  - pybedtools=0.9.1
  - fsspec=2024.3.1
  - s3fs=2024.3.1
